# Generated by Django 3.0.1 on 2020-01-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
