# Generated by Django 3.0.1 on 2020-01-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_dummy_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dummy',
        ),
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
            preserve_default=False,
        ),
    ]
