# Generated by Django 3.0.1 on 2020-01-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20200126_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='hod',
            field=models.BooleanField(default=False),
        ),
    ]
