# Generated by Django 3.0.1 on 2020-03-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_teacher_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='average',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='excellent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='good',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='not_satisfactory',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='poor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='very_good',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
