# Generated by Django 3.0.1 on 2020-03-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_auto_20200304_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='result',
            field=models.FloatField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
