# Generated by Django 3.0.1 on 2020-03-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_auto_20200314_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='suggestions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='coordinator',
            field=models.BooleanField(default=False),
        ),
    ]
