# Generated by Django 3.0.1 on 2020-05-11 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0016_auto_20200511_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.Teacher')),
            ],
            options={
                'unique_together': {('subject', 'batch')},
            },
        ),
    ]
