# Generated by Django 3.0.1 on 2020-05-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0017_batches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batches',
            name='student',
        ),
    ]
