# Generated by Django 3.0.1 on 2020-05-12 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0019_student_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batches',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Subject'),
        ),
        migrations.AlterField(
            model_name='batches',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Teacher'),
        ),
    ]
